version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: teebay-frontend
    environment:
      VITE_GRAPHQL_URI: http://teebay-app:4000/graphql
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - teebay-network
    restart: unless-stopped

networks:
  teebay-network:
    driver: bridge
